<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CSM.BaseGame</RootNamespace>
    <AssemblyName>CSM.BaseGame</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>7.3</LangVersion>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ColossalManaged"><HintPath>$(ManagedDir)\ColossalManaged.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ICities"><HintPath>$(ManagedDir)\ICities.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ManagedDir)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(ManagedDir)\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="protobuf-net"><HintPath>$(CsmDir)\protobuf-net.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="CitiesHarmony.API"><HintPath>$(HarmonyApiDll)</HintPath><Private>false</Private></Reference>
    <Reference Include="CitiesHarmony.Harmony"><HintPath>$(HarmonyDll)</HintPath><Private>false</Private></Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\CSM.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <Net35RefDir>$(PkgMicrosoft_NETFramework_ReferenceAssemblies_net35)build\.NETFramework\v3.5</Net35RefDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>$(Net35RefDir)\mscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>$(Net35RefDir)\System.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(Net35RefDir)\System.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
